on:
  push:
    branches:
      - master

name: build and publish
jobs:
  build-and-publish:
    name: build and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm run build

      - name: publish to prod.
      - run: scp ./build ${{ secrets.LOGIN_CONNECTION_SERVER }}:/var/www/web/build
      - run: ${{ secrets.PASS_CONNECTION_SERVER }}
